//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NuGetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NuGetResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Resources.NuGetResources", typeof(NuGetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; has an additional constraint {1} defined in {2}..
        /// </summary>
        public static string AdditonalConstraintsDefined {
            get {
                return ResourceManager.GetString("AdditonalConstraintsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aggregate queries require at least one OrderBy..
        /// </summary>
        public static string AggregateQueriesRequireOrder {
            get {
                return ResourceManager.GetString("AggregateQueriesRequireOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot create a package that has no dependencies nor content..
        /// </summary>
        public static string CannotCreateEmptyPackage {
            get {
                return ResourceManager.GetString("CannotCreateEmptyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Circular dependency detected &apos;{0}&apos;..
        /// </summary>
        public static string CircularDependencyDetected {
            get {
                return ResourceManager.GetString("CircularDependencyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updating &apos;{0}&apos; to &apos;{1}&apos; failed. Unable to find a version of &apos;{2}&apos; that is compatible with &apos;{1}&apos;..
        /// </summary>
        public static string ConflictErrorWithDependent {
            get {
                return ResourceManager.GetString("ConflictErrorWithDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updating &apos;{0}&apos; to &apos;{1}&apos; failed. Unable to find versions of &apos;{2}&apos; that are compatible with &apos;{1}&apos;..
        /// </summary>
        public static string ConflictErrorWithDependents {
            get {
                return ResourceManager.GetString("ConflictErrorWithDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Added file &apos;{0}&apos;..
        /// </summary>
        public static string Debug_AddedFile {
            get {
                return ResourceManager.GetString("Debug_AddedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Added file &apos;{0}&apos; to folder &apos;{1}&apos;..
        /// </summary>
        public static string Debug_AddedFileToFolder {
            get {
                return ResourceManager.GetString("Debug_AddedFileToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Looking for updates for &apos;{0}&apos;....
        /// </summary>
        public static string Debug_LookingForUpdates {
            get {
                return ResourceManager.GetString("Debug_LookingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removed file &apos;{0}&apos;..
        /// </summary>
        public static string Debug_RemovedFile {
            get {
                return ResourceManager.GetString("Debug_RemovedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removed file &apos;{0}&apos; to folder &apos;{1}&apos;..
        /// </summary>
        public static string Debug_RemovedFileFromFolder {
            get {
                return ResourceManager.GetString("Debug_RemovedFileFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removed folder &apos;{0}&apos;..
        /// </summary>
        public static string Debug_RemovedFolder {
            get {
                return ResourceManager.GetString("Debug_RemovedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;&gt; {0} are being added from &apos;{1}&apos;{2}.
        /// </summary>
        public static string Debug_TargetFrameworkInfo {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assembly references.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_AssemblyReferences {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_AssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Build files.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_BuildFiles {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_BuildFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Content files.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_ContentFiles {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_ContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (not framework-specific).
        /// </summary>
        public static string Debug_TargetFrameworkInfo_NotFrameworkSpecific {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_NotFrameworkSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &gt;&gt; PowerShell scripts are being executed from &apos;{0}&apos;{1}.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_PowershellScripts {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_PowershellScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a For adding package &apos;{0}&apos; to project &apos;{1}&apos; that targets &apos;{2}&apos;,.
        /// </summary>
        public static string Debug_TargetFrameworkInfoPrefix {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dependency &apos;{0}&apos; has an invalid version..
        /// </summary>
        public static string DependencyHasInvalidVersion {
            get {
                return ResourceManager.GetString("DependencyHasInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Child dependencies of dependency only packages cannot mix external and project packages..
        /// </summary>
        public static string DependencyOnlyCannotMixDependencies {
            get {
                return ResourceManager.GetString("DependencyOnlyCannotMixDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading {0} {1}....
        /// </summary>
        public static string DownloadProgressStatus {
            get {
                return ResourceManager.GetString("DownloadProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; already has a dependency defined for &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateDependenciesDefined {
            get {
                return ResourceManager.GetString("DuplicateDependenciesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to load version &apos;{0}&apos; of package &apos;{1}&apos;..
        /// </summary>
        public static string Error_InvalidPackage {
            get {
                return ResourceManager.GetString("Error_InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are no writable config files..
        /// </summary>
        public static string Error_NoWritableConfig {
            get {
                return ResourceManager.GetString("Error_NoWritableConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Package &apos;{0}&apos; already exists..
        /// </summary>
        public static string Error_PackageAlreadyExists {
            get {
                return ResourceManager.GetString("Error_PackageAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Too many automatic redirections were attempted..
        /// </summary>
        public static string Error_TooManyRedirections {
            get {
                return ResourceManager.GetString("Error_TooManyRedirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while loading packages from &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorLoadingPackages {
            get {
                return ResourceManager.GetString("ErrorLoadingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error reading &apos;{0}&apos;..
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to read package from path &apos;{0}&apos;..
        /// </summary>
        public static string ErrorReadingPackage {
            get {
                return ResourceManager.GetString("ErrorReadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a External packages cannot depend on packages that target projects..
        /// </summary>
        public static string ExternalPackagesCannotDependOnProjectLevelPackages {
            get {
                return ResourceManager.GetString("ExternalPackagesCannotDependOnProjectLevelPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File &apos;{0}&apos; already exists in project &apos;{1}&apos;. Do you want to overwrite it?.
        /// </summary>
        public static string FileConflictMessage {
            get {
                return ResourceManager.GetString("FileConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File &apos;{0}&apos; does not exist..
        /// </summary>
        public static string FileDoesNotExit {
            get {
                return ResourceManager.GetString("FileDoesNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;packages&apos; and &apos;versionConstraints&apos; parameters must have the same number of elements..
        /// </summary>
        public static string GetUpdatesParameterMismatch {
            get {
                return ResourceManager.GetString("GetUpdatesParameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The schema version of &apos;{0}&apos; is incompatible with version {1} of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942..
        /// </summary>
        public static string IncompatibleSchema {
            get {
                return ResourceManager.GetString("IncompatibleSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Overwrite existing file &apos;{0}&apos;..
        /// </summary>
        public static string Info_OverwriteExistingFile {
            get {
                return ResourceManager.GetString("Info_OverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not connect to the feed specified at &apos;{0}&apos;. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity..
        /// </summary>
        public static string InvalidFeed {
            get {
                return ResourceManager.GetString("InvalidFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid framework name format. Expected {framework}{version}-{profile}..
        /// </summary>
        public static string InvalidFrameworkNameFormat {
            get {
                return ResourceManager.GetString("InvalidFrameworkNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;{0}&quot; cannot be called on a NullSettings. This may be caused on account of insufficient permissions to read or write to &quot;%AppData%\NuGet\NuGet.config&quot;..
        /// </summary>
        public static string InvalidNullSettingsOperation {
            get {
                return ResourceManager.GetString("InvalidNullSettingsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The package ID &apos;{0}&apos; contains invalid characters. Examples of valid package IDs include &apos;MyPackage&apos; and &apos;MyPackage.Sample&apos;..
        /// </summary>
        public static string InvalidPackageId {
            get {
                return ResourceManager.GetString("InvalidPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; is not a valid version string..
        /// </summary>
        public static string InvalidVersionString {
            get {
                return ResourceManager.GetString("InvalidVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Applying constraint &apos;{0} {1}&apos; defined in {2}..
        /// </summary>
        public static string Log_ApplyingConstraints {
            get {
                return ResourceManager.GetString("Log_ApplyingConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attempting to resolve dependency &apos;{0}&apos;..
        /// </summary>
        public static string Log_AttemptingToRetrievePackageFromSource {
            get {
                return ResourceManager.GetString("Log_AttemptingToRetrievePackageFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adding &apos;{0}&apos; to {1}..
        /// </summary>
        public static string Log_BeginAddPackageReference {
            get {
                return ResourceManager.GetString("Log_BeginAddPackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Installing &apos;{0}&apos;..
        /// </summary>
        public static string Log_BeginInstallPackage {
            get {
                return ResourceManager.GetString("Log_BeginInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removing &apos;{0}&apos; from {1}..
        /// </summary>
        public static string Log_BeginRemovePackageReference {
            get {
                return ResourceManager.GetString("Log_BeginRemovePackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uninstalling &apos;{0}&apos;..
        /// </summary>
        public static string Log_BeginUninstallPackage {
            get {
                return ResourceManager.GetString("Log_BeginUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Install &apos;{0}&apos;.
        /// </summary>
        public static string Log_InstallPackage {
            get {
                return ResourceManager.GetString("Log_InstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add &apos;{0}&apos; to project {1}..
        /// </summary>
        public static string Log_InstallPackageIntoProject {
            get {
                return ResourceManager.GetString("Log_InstallPackageIntoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No updates available for &apos;{0}&apos;..
        /// </summary>
        public static string Log_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Log_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No updates available for &apos;{0}&apos; in project &apos;{1}&apos;..
        /// </summary>
        public static string Log_NoUpdatesAvailableForProject {
            get {
                return ResourceManager.GetString("Log_NoUpdatesAvailableForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; already installed..
        /// </summary>
        public static string Log_PackageAlreadyInstalled {
            get {
                return ResourceManager.GetString("Log_PackageAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully installed &apos;{0}&apos;..
        /// </summary>
        public static string Log_PackageInstalledSuccessfully {
            get {
                return ResourceManager.GetString("Log_PackageInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} already has a reference to &apos;{1}&apos;..
        /// </summary>
        public static string Log_ProjectAlreadyReferencesPackage {
            get {
                return ResourceManager.GetString("Log_ProjectAlreadyReferencesPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully added &apos;{0}&apos; to {1}..
        /// </summary>
        public static string Log_SuccessfullyAddedPackageReference {
            get {
                return ResourceManager.GetString("Log_SuccessfullyAddedPackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully removed &apos;{0}&apos; from {1}..
        /// </summary>
        public static string Log_SuccessfullyRemovedPackageReference {
            get {
                return ResourceManager.GetString("Log_SuccessfullyRemovedPackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully uninstalled &apos;{0}&apos;..
        /// </summary>
        public static string Log_SuccessfullyUninstalledPackage {
            get {
                return ResourceManager.GetString("Log_SuccessfullyUninstalledPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uninstall &apos;{0}&apos;..
        /// </summary>
        public static string Log_UninstallPackage {
            get {
                return ResourceManager.GetString("Log_UninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove &apos;{0}&apos; from project {1}..
        /// </summary>
        public static string Log_UninstallPackageFromProject {
            get {
                return ResourceManager.GetString("Log_UninstallPackageFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updating &apos;{0}&apos; from version &apos;{1}&apos; to &apos;{2}&apos; in project &apos;{3}&apos;..
        /// </summary>
        public static string Log_UpdatingPackages {
            get {
                return ResourceManager.GetString("Log_UpdatingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updating &apos;{0}&apos; to version &apos;{1}&apos; in project &apos;{2}&apos;..
        /// </summary>
        public static string Log_UpdatingPackagesWithoutOldVersion {
            get {
                return ResourceManager.GetString("Log_UpdatingPackagesWithoutOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assembly name is required..
        /// </summary>
        public static string Manifest_AssemblyNameRequired {
            get {
                return ResourceManager.GetString("Manifest_AssemblyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;dependencies&gt; element must not contain both &lt;group&gt; and &lt;dependency&gt; child elements..
        /// </summary>
        public static string Manifest_DependenciesHasMixedElements {
            get {
                return ResourceManager.GetString("Manifest_DependenciesHasMixedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dependency Id is required..
        /// </summary>
        public static string Manifest_DependencyIdRequired {
            get {
                return ResourceManager.GetString("Manifest_DependencyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude path &apos;{0}&apos; contains invalid characters..
        /// </summary>
        public static string Manifest_ExcludeContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Manifest_ExcludeContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id must not exceed 100 characters..
        /// </summary>
        public static string Manifest_IdMaxLengthExceeded {
            get {
                return ResourceManager.GetString("Manifest_IdMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;minClientVersion&apos; attribute in the package manifest has invalid value. It must be a valid version string..
        /// </summary>
        public static string Manifest_InvalidMinClientVersion {
            get {
                return ResourceManager.GetString("Manifest_InvalidMinClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency &quot;{0}&quot; or update the version field..
        /// </summary>
        public static string Manifest_InvalidPrereleaseDependency {
            get {
                return ResourceManager.GetString("Manifest_InvalidPrereleaseDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid assembly reference &apos;{0}&apos;. Ensure that a file named &apos;{0}&apos; exists in the lib directory..
        /// </summary>
        public static string Manifest_InvalidReference {
            get {
                return ResourceManager.GetString("Manifest_InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assembly reference &apos;{0}&apos; contains invalid characters..
        /// </summary>
        public static string Manifest_InvalidReferenceFile {
            get {
                return ResourceManager.GetString("Manifest_InvalidReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid schema namespace &apos;{0}&apos;..
        /// </summary>
        public static string Manifest_InvalidSchemaNamespace {
            get {
                return ResourceManager.GetString("Manifest_InvalidSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The manifest of this package has not been read. Call ReadManifest() before calling this method..
        /// </summary>
        public static string Manifest_NotAvailable {
            get {
                return ResourceManager.GetString("Manifest_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not find manifest file at &apos;{0}&apos;..
        /// </summary>
        public static string Manifest_NotFound {
            get {
                return ResourceManager.GetString("Manifest_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;references&gt; element must not contain both &lt;group&gt; and &lt;reference&gt; child elements..
        /// </summary>
        public static string Manifest_ReferencesHasMixedElements {
            get {
                return ResourceManager.GetString("Manifest_ReferencesHasMixedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The element package\metadata\references\group must contain at least one &lt;reference&gt; child element..
        /// </summary>
        public static string Manifest_ReferencesIsEmpty {
            get {
                return ResourceManager.GetString("Manifest_ReferencesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The required element &apos;{0}&apos; is missing from the manifest..
        /// </summary>
        public static string Manifest_RequiredElementMissing {
            get {
                return ResourceManager.GetString("Manifest_RequiredElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} is required..
        /// </summary>
        public static string Manifest_RequiredMetadataMissing {
            get {
                return ResourceManager.GetString("Manifest_RequiredMetadataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enabling license acceptance requires a license url..
        /// </summary>
        public static string Manifest_RequireLicenseAcceptanceRequiresLicenseUrl {
            get {
                return ResourceManager.GetString("Manifest_RequireLicenseAcceptanceRequiresLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Source path &apos;{0}&apos; contains invalid characters..
        /// </summary>
        public static string Manifest_SourceContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Manifest_SourceContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Target path &apos;{0}&apos; contains invalid characters..
        /// </summary>
        public static string Manifest_TargetContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Manifest_TargetContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} cannot be empty..
        /// </summary>
        public static string Manifest_UriCannotBeEmpty {
            get {
                return ResourceManager.GetString("Manifest_UriCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Framework name is missing..
        /// </summary>
        public static string MissingFrameworkName {
            get {
                return ResourceManager.GetString("MissingFrameworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Already referencing a newer version of &apos;{0}&apos;..
        /// </summary>
        public static string NewerVersionAlreadyReferenced {
            get {
                return ResourceManager.GetString("NewerVersionAlreadyReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File not found: &apos;{0}&apos;..
        /// </summary>
        public static string PackageAuthoring_FileNotFound {
            get {
                return ResourceManager.GetString("PackageAuthoring_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Package does not contain a manifest..
        /// </summary>
        public static string PackageDoesNotContainManifest {
            get {
                return ResourceManager.GetString("PackageDoesNotContainManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to uninstall &apos;{0}&apos; because &apos;{1}&apos; depends on it..
        /// </summary>
        public static string PackageHasDependent {
            get {
                return ResourceManager.GetString("PackageHasDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to uninstall &apos;{0}&apos; because &apos;{1}&apos; depend on it..
        /// </summary>
        public static string PackageHasDependents {
            get {
                return ResourceManager.GetString("PackageHasDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;{0}&apos; package requires NuGet client version &apos;{1}&apos; or above, but the current NuGet version is &apos;{2}&apos;..
        /// </summary>
        public static string PackageMinVersionNotSatisfied {
            get {
                return ResourceManager.GetString("PackageMinVersionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Allow NuGet to download missing packages.
        /// </summary>
        public static string PackageRestoreConsentCheckBoxText {
            get {
                return ResourceManager.GetString("PackageRestoreConsentCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to process request. &apos;{0}&apos;. 
        ///{1}..
        /// </summary>
        public static string PackageServerError {
            get {
                return ResourceManager.GetString("PackageServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The profile part of a portable target framework must not contain empty component..
        /// </summary>
        public static string PortableFrameworkProfileComponentIsEmpty {
            get {
                return ResourceManager.GetString("PortableFrameworkProfileComponentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The profile part of a portable target framework must not contain a portable framework component..
        /// </summary>
        public static string PortableFrameworkProfileComponentIsPortable {
            get {
                return ResourceManager.GetString("PortableFrameworkProfileComponentIsPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portable target framework must not have an empty profile part..
        /// </summary>
        public static string PortableFrameworkProfileEmpty {
            get {
                return ResourceManager.GetString("PortableFrameworkProfileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The profile part of a portable target framework must not contain the &apos;-&apos; character..
        /// </summary>
        public static string PortableFrameworkProfileHasDash {
            get {
                return ResourceManager.GetString("PortableFrameworkProfileHasDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The profile part of a portable target framework must not contain empty space..
        /// </summary>
        public static string PortableFrameworkProfileHasSpace {
            get {
                return ResourceManager.GetString("PortableFrameworkProfileHasSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Portable Profile Table must be specified when resolving the short name of a portable profile..
        /// </summary>
        public static string PortableProfileTableMustBeSpecified {
            get {
                return ResourceManager.GetString("PortableProfileTableMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;portableProfileTable&apos; parameter must be provided when getting the short name for a Portable target framework.
        /// </summary>
        public static string PortableProfileTableRequiresForGetShortFrameworkName {
            get {
                return ResourceManager.GetString("PortableProfileTableRequiresForGetShortFrameworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} does not reference &apos;{1}&apos;..
        /// </summary>
        public static string ProjectDoesNotHaveReference {
            get {
                return ResourceManager.GetString("ProjectDoesNotHaveReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to parse developmentDependency value &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        public static string ReferenceFile_InvalidDevelopmentFlag {
            get {
                return ResourceManager.GetString("ReferenceFile_InvalidDevelopmentFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to parse requireReinstallation value &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        public static string ReferenceFile_InvalidRequireReinstallationFlag {
            get {
                return ResourceManager.GetString("ReferenceFile_InvalidRequireReinstallationFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to parse version value &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        public static string ReferenceFile_InvalidVersion {
            get {
                return ResourceManager.GetString("ReferenceFile_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The special version part cannot exceed 20 characters..
        /// </summary>
        public static string SemVerSpecialVersionTooLong {
            get {
                return ResourceManager.GetString("SemVerSpecialVersionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Using credentials from config or environment. UserName: {0}.
        /// </summary>
        public static string SettingsCredentials_UsingSavedCredentials {
            get {
                return ResourceManager.GetString("SettingsCredentials_UsingSavedCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One of the supported framework is null..
        /// </summary>
        public static string SupportedFrameworkIsNull {
            get {
                return ResourceManager.GetString("SupportedFrameworkIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The replacement token &apos;{0}&apos; has no value..
        /// </summary>
        public static string TokenHasNoValue {
            get {
                return ResourceManager.GetString("TokenHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type to compare must be an instance of SemanticVersion..
        /// </summary>
        public static string TypeMustBeASemanticVersion {
            get {
                return ResourceManager.GetString("TypeMustBeASemanticVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not install package &apos;{0}&apos;. You are trying to install this package into a project that targets &apos;{1}&apos;, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author..
        /// </summary>
        public static string UnableToFindCompatibleItems {
            get {
                return ResourceManager.GetString("UnableToFindCompatibleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to locate dependency &apos;{0}&apos;. It may have been uninstalled..
        /// </summary>
        public static string UnableToLocateDependency {
            get {
                return ResourceManager.GetString("UnableToLocateDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connection to feed &apos;{0}&apos; requires the Windows Identity Foundation runtime to be installed. .
        /// </summary>
        public static string UnableToLocateWIF {
            get {
                return ResourceManager.GetString("UnableToLocateWIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to resolve dependency &apos;{0}&apos;..
        /// </summary>
        public static string UnableToResolveDependency {
            get {
                return ResourceManager.GetString("UnableToResolveDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to resolve &apos;{0}&apos;..
        /// </summary>
        public static string UnableToResolveUri {
            get {
                return ResourceManager.GetString("UnableToResolveUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to find package &apos;{0}&apos;..
        /// </summary>
        public static string UnknownPackage {
            get {
                return ResourceManager.GetString("UnknownPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to find version &apos;{1}&apos; of package &apos;{0}&apos;..
        /// </summary>
        public static string UnknownPackageSpecificVersion {
            get {
                return ResourceManager.GetString("UnknownPackageSpecificVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown schema version &apos;{0}&apos;..
        /// </summary>
        public static string UnknownSchemaVersion {
            get {
                return ResourceManager.GetString("UnknownSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hash algorithm &apos;{0}&apos; is unsupported. Supported algorithms include: SHA512 and SHA256..
        /// </summary>
        public static string UnsupportedHashAlgorithm {
            get {
                return ResourceManager.GetString("UnsupportedHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to parse config file &apos;{0}&apos;..
        /// </summary>
        public static string UserSettings_UnableToParseConfigFile {
            get {
                return ResourceManager.GetString("UserSettings_UnableToParseConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; already exists. Skipping....
        /// </summary>
        public static string Warning_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Warning_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skipping &apos;{0}&apos; because it was modified..
        /// </summary>
        public static string Warning_FileModified {
            get {
                return ResourceManager.GetString("Warning_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; skipped, because it is in use by &apos;{1}&apos;..
        /// </summary>
        public static string Warning_PackageSkippedBecauseItIsInUse {
            get {
                return ResourceManager.GetString("Warning_PackageSkippedBecauseItIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uninstalling &apos;{0}&apos; might cause &apos;{1}&apos; to be broken..
        /// </summary>
        public static string Warning_UninstallingPackageWillBreakDependents {
            get {
                return ResourceManager.GetString("Warning_UninstallingPackageWillBreakDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while applying transformation to &apos;{0}&apos; in project &apos;{1}&apos;:.
        /// </summary>
        public static string XdtError {
            get {
                return ResourceManager.GetString("XdtError", resourceCulture);
            }
        }
    }
}
